import * as Print from "expo-print";
import * as Sharing from "expo-sharing";

export async function sharePdf(title: string, htmlBody: string) {
  const html = `
  <html>
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width,initial-scale=1" />
      <style>
        body { font-family: -apple-system, system-ui, Segoe UI, Roboto, Arial; padding: 22px; color: #0B1220; }
        h1 { font-size: 22px; margin: 0 0 8px 0; }
        h2 { font-size: 16px; margin: 18px 0 6px 0; }
        p, li { font-size: 13px; line-height: 18px; color: #0F172A; }
        .muted { color: #64748B; font-size: 12px; }
        .box { border: 1px solid #E5E7EB; border-radius: 12px; padding: 12px; background: #F8FAFC; }
        a { color: #1D4ED8; }
      </style>
    </head>
    <body>
      <h1>${escapeHtml(title)}</h1>
      ${htmlBody}
      <p class="muted">Generated by Waspada. This is informational guidance, not official advice. For urgent cases, contact your bank and the authorities.</p>
    </body>
  </html>
  `;

  const file = await Print.printToFileAsync({ html });
  await Sharing.shareAsync(file.uri);
}

function escapeHtml(s: string) {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
